name: datasciencejosepy
channels:
  - defaults
dependencies:
  - argon2-cffi-bindings=25.1.0=py313h02ab6af_0
  - asttokens=3.0.0=py313haa95532_0
  - async-lru=2.0.5=py313haa95532_0
  - attrs=25.4.0=py313haa95532_1
  - blinker=1.9.0=py313haa95532_0
  - brotlicffi=1.0.9.2=py313h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - certifi=2025.11.12=py313haa95532_0
  - cffi=2.0.0=py313h02ab6af_1
  - charset-normalizer=3.4.4=py313haa95532_0
  - click=8.2.1=py313haa95532_0
  - colorama=0.4.6=py313haa95532_0
  - decorator=5.2.1=py313haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distlib=0.3.8=py313haa95532_0
  - executing=2.2.1=py313haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - filelock=3.17.0=py313haa95532_0
  - flask=3.1.2=py313haa95532_0
  - h11=0.16.0=py313haa95532_1
  - httpcore=1.0.9=py313haa95532_0
  - httpx=0.28.1=py313haa95532_1
  - idna=3.11=py313haa95532_0
  - ipython_pygments_lexers=1.1.1=py313haa95532_0
  - itsdangerous=2.2.0=py313haa95532_0
  - jedi=0.19.2=py313haa95532_0
  - jinja2=3.1.6=py313haa95532_0
  - jupyter_client=8.6.3=py313haa95532_0
  - jupyter_core=5.8.1=py313haa95532_0
  - jupyter_events=0.12.0=py313haa95532_0
  - jupyter_server=2.16.0=py313haa95532_0
  - jupyter_server_terminals=0.5.3=py313haa95532_0
  - jupyterlab_pygments=0.3.0=py313haa95532_0
  - jupyterlab_server=2.28.0=py313haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libmpdec=4.0.0=h827c3e9_0
  - libsodium=1.0.20=h83e8143_0
  - libzlib=1.3.1=h02ab6af_0
  - nbclient=0.10.2=py313haa95532_0
  - nbconvert-core=7.16.6=py313haa95532_0
  - nbformat=5.10.4=py313haa95532_0
  - nest-asyncio=1.6.0=py313haa95532_0
  - notebook-shim=0.2.4=py313haa95532_0
  - openssl=3.0.18=h543e019_0
  - overrides=7.4.0=py313haa95532_0
  - packaging=25.0=py313haa95532_1
  - pandocfilters=1.5.1=py313haa95532_0
  - pip=25.2=pyhc872135_1
  - pipenv=2025.0.4=py313haa95532_0
  - prometheus_client=0.21.1=py313haa95532_0
  - prompt-toolkit=3.0.52=py313haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - pure_eval=0.2.3=py313haa95532_0
  - pycparser=2.23=py313haa95532_0
  - pysocks=1.7.1=py313haa95532_1
  - python=3.13.9=h260b955_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-fastjsonschema=2.20.0=py313haa95532_0
  - python_abi=3.13=1_cp313
  - pywin32=311=py313h885b0b7_0
  - pyzmq=27.1.0=py313h7149c55_0
  - requests=2.32.5=py313haa95532_0
  - rfc3339-validator=0.1.4=py313haa95532_0
  - rfc3986-validator=0.1.1=py313haa95532_0
  - setuptools=80.9.0=py313haa95532_0
  - six=1.17.0=py313haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=py313haa95532_0
  - terminado=0.18.1=py313haa95532_0
  - tinycss2=1.4.0=py313haa95532_0
  - tk=8.6.15=hf199647_0
  - traitlets=5.14.3=py313haa95532_0
  - typing-extensions=4.15.0=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py313haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - virtualenv=20.28.0=py313haa95532_0
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - waitress=3.0.2=py313haa95532_0
  - webencodings=0.5.1=py313haa95532_2
  - werkzeug=3.1.3=py313haa95532_0
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_1
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - arrow==1.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.17
      - et-xmlfile==2.0.0
      - fastjsonschema==2.21.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - ipykernel==7.1.0
      - ipython==9.6.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyterlab==4.4.10
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lxml==6.0.2
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - notebook==7.4.7
      - numpy==2.1.3
      - openpyxl==3.1.5
      - pandas==2.2.3
      - parso==0.8.5
      - patsy==1.0.2
      - pillow==11.0.0
      - platformdirs==4.5.0
      - prometheus-client==0.23.1
      - psutil==7.1.3
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.36
      - statsmodels==0.14.5
      - threadpoolctl==3.6.0
      - tornado==6.5.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - xgboost==3.1.1
prefix: C:\Users\HP\anaconda3\envs\datasciencejosepy
